### ISSUE TITLE
Gifting Hearts

### ISSUE THREAD

**Issue by RandomFulTTV** [Tater-Certified/LifeSteal#4]
So me and a friend went through the code and found that there's heart ore, heart items, and bunch of stuff. But I can't get it to work! I need gifting heart for my server.

**Comment by QPCrummer** [comment]
You can use an altar to gift hearts to players. Just rename the heart item to the name of the player and shift right click on an altar to gift that heart to the player. 

As of my latest pushes on the 1.20.1 branch of this mod, you can also use `/gift <Username> <Amount of Hearts>`  to gift hearts to players as well.
