### ISSUE TITLE
I cant get any items 

### ISSUE THREAD

**Issue by Doddik911** [Tater-Certified/LifeSteal#7]
So i just dont know how to get heart items and i gant find ores il try to keep updated

**Comment by Doddik911** [comment]
ok so now when i got the items thru commands but now when i try to revive my friend it still says he needs to be revived

**Comment by Doddik911** [comment]
ok ig i fixed it but i dont think i can find the items natuarly spawning

**Comment by Doddik911** [comment]
ok so nvm i remember the ore spawning naturally before i just didnt have the recorce pack on but now idk how to mine the ore 
cuz when i use my pickaxe it just disappears

**Comment by QPCrummer** [comment]
[lifesteal_example_pack.zip](https://github.com/user-attachments/files/17551821/lifesteal_example_pack.zip)
Try using this datapack. I assume you are using the 1.21 version of this mod. It is not considered stable as 1.21 broke many aspects of the mod. The inconsistency of reviving is also a known issue.

**Comment by Doddik911** [comment]
im running it off of fabric will it still work and if i switch to that version of the mod/ data pack will it reset everyones hearts

**Comment by QPCrummer** [comment]
What Minecraft version are you currently using? That datapack I sent only works on MC 1.21. It must be used with the Lifesteal mod in order to fix the item dropping issues.

 And no, adding that datapack will not reset everyone’s hearts. Upgrading to a newer version of the mod probably will reset everyone’s hearts though.

**Comment by Doddik911** [comment]
ok so 2 quick questions. A does the data pack work on 1.21.1 and etc and B do the people on the server need to install the data pack beacuse even after installing the data pack into the server it still takes VERY long to mine the ore and after mining it it drops nothing (unless you have to mine it in a specific way and i just dont know)

**Comment by Doddik911** [comment]
because im also running the server with the geyser mc mod so idk if that maybe messes with things

**Comment by QPCrummer** [comment]
This issue should be solved in version 2.0.0. 
I could not replicate mining and item dropping issues. I’ll be closing this as completed, but feel free to reopen it if the issue persists.
